openapi: 3.0.1
info:
  title: Discord bot api
  description: An api for interfacing with the clangen discord bot
  version: v1

servers:
  - url: http://localhost:8080
    description: Development server
paths:
  /logs:
    post:
      tags:
        - Clangen > Server
      summary: >-
        Attaches a list of files to the specified artifact of the specified
        release in the specified channel.
      parameters:
        - name: token
          in: header
          description: ''
          required: true
          style: simple
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                logs:
                  type: array
                  items:
                    type: string
                    format: binary
            encoding:
              fileBundle:
                style: form
      responses:
        '200':
          description: Success
        '401':
          description: Invalid Token
        '400':
          description: No Logs
  /release:
    post:
      tags:
        - Update API > Server
      summary: >-
        Posts release notes in the respective channel.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                version:
                  type: string
                upstream:
                  type: string
                releaselinks:
                  type: array
                  items:
                    type: string
                changelog:
                  type: string
                channel:
                  type: string
      responses:
        '200':
          description: Success
components: {}
